//
//  USHuoShanDefines.h
//  USReader
//
//  Created by nongyun.cao on 2024/1/8.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

// User Info
FOUNDATION_EXPORT NSString * const SDEF_UID;

// Online & Resource Authentication
FOUNDATION_EXPORT NSString * const SDEF_APPID;
FOUNDATION_EXPORT NSString * const SDEF_TOKEN;

// Offline Authentication
FOUNDATION_EXPORT NSString * const SDEF_LICENSE_NAME;
FOUNDATION_EXPORT NSString * const SDEF_LICENSE_BUSI_ID;

// Address
FOUNDATION_EXPORT NSString * const SDEF_DEFAULT_ADDRESS;
FOUNDATION_EXPORT NSString * const SDEF_DEFAULT_HTTP_ADDRESS;

// TTS
FOUNDATION_EXPORT NSString * const SDEF_TTS_DEFAULT_URI;
FOUNDATION_EXPORT NSString * const SDEF_TTS_DEFAULT_CLUSTER;
FOUNDATION_EXPORT NSString * const SDEF_TTS_DEFAULT_ONLINE_VOICE;
FOUNDATION_EXPORT NSString * const SDEF_TTS_DEFAULT_ONLINE_VOICE_TYPE;
FOUNDATION_EXPORT NSString * const SDEF_TTS_DEFAULT_OFFLINE_VOICE;
FOUNDATION_EXPORT NSString * const SDEF_TTS_DEFAULT_OFFLINE_VOICE_TYPE;
FOUNDATION_EXPORT NSString * const SDEF_TTS_DEFAULT_ONLINE_LANGUAGE;
FOUNDATION_EXPORT NSString * const SDEF_TTS_DEFAULT_OFFLINE_LANGUAGE;
FOUNDATION_EXPORT const NSArray* SDEF_TTS_DEFAULT_DOWNLOAD_OFFLINE_VOICES();

// ASR
FOUNDATION_EXPORT NSString * const SDEF_ASR_DEFAULT_CLUSTER;
FOUNDATION_EXPORT NSString * const SDEF_ASR_DEFAULT_URI;

// VoiceClone
FOUNDATION_EXPORT NSString * const SDEF_VOICECLONE_DEFAULT_UIDS;

// VoiceConv
FOUNDATION_EXPORT NSString * const SDEF_VOICECONV_DEFAULT_URI;

@interface USHuoShanDefines : NSObject

@end

NS_ASSUME_NONNULL_END
